### ISSUE TITLE
Business Evaluation

### ISSUE THREAD

**Issue by LucienLee** [godgunman/tii#4]
1. 多少錢 / 怎麼賺錢 / Target users & use case  
   付費方式 -> 年費？ 一次性額外機票費用？
2. How to make sure the security?  
   主要是說服 finavia 接受 uber 運送以及運送財產保險問題，設計 Safety Check 問卷，確保運送過程的責任歸屬
3. 找uber的人聊聊security + delivery 的問題

**Comment by youwenliang** [comment]
付費方式：
1. 訂機票時加錢訂服務
2. 訂完機票後 提供選項增加服務 再付錢
3. 坐飛機當天付費使用此服務
4. 提供年/月費選項給經常顧客

費用：
Uber運送費用一次約10 ~ 20EUR
假設一台Uber可以一次載兩～三件行李，所以平均每人付4~7EUR左右
因此可以定價在機票錢＋10~15EUR可提供此向服務

**Comment by youwenliang** [comment]
Uber:

What do you do to guarantee safe & reliable delivery?

All of our delivery partners undergo a comprehensive background check and ongoing quality checks through our ratings system. With UberRUSH real-time tracking, you can always follow your deliveries from pickup to dropoff. If you have any questions or concerns, you can contact our support team.

UBERRUSH QUALITY

To maintain the Uber standard you’re used to, all messengers pass Uber’s rigorous screening process. In order to be an UberRUSH partner, individuals must pass:

A stringent background check
An in-person interview and screening
Ongoing quality controls
